name: example-workflow
on: [push]
jobs:
  run-anchor-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn install

      - name: Set up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          rustc --version
          cargo --version

      - name: Set up Anchor CLI
        uses: metaDAOproject/setup-anchor@v2.1
        with:
          anchor-version: "0.30.1"
          solana-cli-version: "1.18.25"
          node-version: "20"

      # Explicitly add Solana CLI to the PATH again
      - run: |
          export PATH="/root/.local/share/solana/install/active_release/bin:$PATH"
          source ~/.bashrc
          ls -la
          anchor build
          anchor test
