name: Anchor Build and Test Workflow

on:
  push:
    branches: [testing-action]

jobs:
  run-anchor-container:
    runs-on: ubuntu-latest
    container:
      image: backpackapp/build:v0.30.1

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Set Rust toolchain to stable (fixes the rustup issue)
      - name: Set default Rust toolchain
        run: |
          rustup default stable
          rustup show

      - name: Install dependencies
        run: |
          yarn install

      - name: Run Anchor Build
        run: |
          ls -la 
          pwd
          anchor build
      - name: Generating Solana keypair
        run: |
          solana-keygen new --no-bip39-passphrase --force
          solana address
        #   KeyPair location -> /github/home/.config/solana/id.json

      - name: Create degen_pools-keypair.json from secret
        env:
          PROGRAM_KEYPAIR_JSON: ${{ secrets.PROGRAM_KEYPAIR_JSON }}
        run: |
          echo "$PROGRAM_KEYPAIR_JSON" > target/deploy/degen_pools-keypair.json
          pwd
          ls -la
          cat target/deploy/degen_pools-keypair.json

      - name: Runing Test
        run: anchor test
